[package]
name = "bark-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[[bin]]
name = "BARK"
path = "src/main.rs"

[dependencies]
bark-core = { workspace = true }
bark-media = { workspace = true }
bark-node = { workspace = true }
bark-proto = { workspace = true }
tokio = { version = "1.53.1", features = ["sync"] }
tracing = "0.1.44"

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Threading",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]
